name: Build All Tweaks
permissions:
  contents: write

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        project:
          - Nita
    steps:
      - uses: actions/checkout@v4

      - name: Set up Theos
        uses: waruhachi/theos-action@v2.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          theos-src: "roothide/theos"

      - name: Build Package
        shell: bash
        working-directory: ${{ matrix.project }}
        run: |
          make clean package FINALPACKAGE=1
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}-artifacts
          path: ${{ matrix.project }}/packages/*.deb

  release:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./packages

      - name: Extract Variables and Compute Hashes
        id: metadata
        shell: bash
        run: |
          for PROJECT in ./packages/*; do
              if [ -d "$PROJECT" ]; then
                  PROJECT_NAME=$(basename "$PROJECT")
                  for FILE in "$PROJECT"/*.deb; do
                      FILENAME=$(basename "$FILE")
                      ARCH=$(echo "$FILENAME" | sed -E 's/.*_iphoneos-(arm|arm64|arm64e)\.deb/\1/')

                      echo "${PROJECT_NAME}_${ARCH}_MD5SUM=$(md5 -q "$FILE")" >> "$GITHUB_ENV"
                      echo "${PROJECT_NAME}_${ARCH}_SHA1=$(shasum -a 1 "$FILE" | awk '{ print $1 }')" >> "$GITHUB_ENV"
                      echo "${PROJECT_NAME}_${ARCH}_SHA256=$(shasum -a 256 "$FILE" | awk '{ print $1 }')" >> "$GITHUB_ENV"
                  done
              fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          name: Release
          body: |
            ## Build Summary

            ### Projects
            {%- for PROJECT in projects %}
            #### {{ PROJECT }}
            iphoneos-arm:
              MD5sum: ${{ env[PROJECT + "_ARM_MD5SUM"] }}
              SHA1: ${{ env[PROJECT + "_ARM_SHA1"] }}
              SHA256: ${{ env[PROJECT + "_ARM_SHA256"] }}

            iphoneos-arm64:
              MD5sum: ${{ env[PROJECT + "_ARM64_MD5SUM"] }}
              SHA1: ${{ env[PROJECT + "_ARM64_SHA1"] }}
              SHA256: ${{ env[PROJECT + "_ARM64_SHA256"] }}

            iphoneos-arm64e:
              MD5sum: ${{ env[PROJECT + "_ARM64E_MD5SUM"] }}
              SHA1: ${{ env[PROJECT + "_ARM64E_SHA1"] }}
              SHA256: ${{ env[PROJECT + "_ARM64E_SHA256"] }}
            {%- endfor %}
          files: ./packages/**/*.deb
          draft: false
          prerelease: false
          make_latest: true
